project:
  type: website
  output-dir: "docs"

website:
  title: "Buntubethu Sydney Malunga"
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "CV"
        file: cv.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/buntumalunga
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cyborg
    css: styles.css

editor: visual

